-d C:\Users\emirh\traffic_lights\impl\gwsynthesis\traffic_lights.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\emirh\traffic_lights\src\traffic_lights.cst
-cfg C:\Users\emirh\traffic_lights\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
